### ISSUE TITLE
Crash when playing "Oops I did it again" by the bot using sound cloud

### ISSUE THREAD

**Issue by CakeOfPain** [Evolinox/SpookBot#8]
## The Issue

I tried playing the famous Song "Oops I did it again" by Britney Spears and the Bot crashed. :) Maybe someone could help me or fix it?

## Error in the console
```
[lava-daemon-pool-info-loader-2-thread-1] WARN com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager - Suspicious exception for loading item https://soundcloud.com/britneyspears/oops-i-did-it-again-album
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This url does not appear to be a playable track.
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.DefaultSoundCloudHtmlDataLoader.load(DefaultSoundCloudHtmlDataLoader.java:43)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadFromTrackPage(SoundCloudAudioSourceManager.java:202)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.processAsSingleTrack(SoundCloudAudioSourceManager.java:179)
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadItem(SoundCloudAudioSourceManager.java:116)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.77
  os.arch: aarch64
  os.name: Mac OS X
  os.version: 14.4.1
  java.vendor: Homebrew
  java.version: 11.0.23
  java.runtime.version: 11.0.23+0
  java.vm.version: 11.0.23+0
Caused by: java.lang.RuntimeException: No track JSON found EID: 5449a919-a7e1-44e5-8c14-b981786b5c55, html <redacted>
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134)
        ... 13 more
Apr. 22, 2024 12:04:49 VORM. Music.player$1 loadFailed
SCHWERWIEGEND: Loading Track failed: This url does not appear to be a playable track.
Apr. 22, 2024 12:04:50 VORM. Commands.music onSlashCommandInteraction
INFORMATION: Playing https://soundcloud.com/britneyspears/oops-i-did-it-again-album
```

**Comment by CakeOfPain** [comment]
Also here is the Link I gave the command: https://soundcloud.com/britneyspears/oops-i-did-it-again-album

**Comment by Evolinox** [comment]
The Issue here is your Link, I think. It links to an Album instead of a Track... And Albums aren't supported by SpookBot and Lavaplayer.
